### PR TITLE
Add error checking when shelling out

### PR DESCRIPTION
**Pull request by adthrasher**
When running with insufficient memory, shelling out can fail when the main process reaches 50% of system memory. Without error checking, this fails in unexpected ways. Instead, each time the perl code shells out, it needs to check the return code and propagate.

### CODE REVIEW

**Comment by adthrasher** [comment]
@drjrm3 - Can someone from your team validate that this catches the error in the clinical environment?

**Comment by drkennetz** [comment]
Overall the code looks good. This will need to be tested either in SJCloud or CycleCloud because this should not actually die on-prem. @drjrm3 what do you think?

**Comment by drjrm3** [comment]
> @drjrm3 - Can someone from your team validate that this catches the error in the clinical environment?

Sure - I'll ask @atrull314 to test this out on prem since we know of a sample where this happens.

**Comment by atrull314** [comment]
> > @drjrm3 - Can someone from your team validate that this catches the error in the clinical environment?
> 
> Sure - I'll ask @atrull314 to test this out on prem since we know of a sample where this happens.

Alright testing looked good. The pipeline failed with Exit code 12, and with the error message: 'Error running assembler: Cannot allocate memory'

**Comment by drjrm3** [comment]
Thanks @atrull314. @adthrasher - ready to merge as far as I'm concerned. Thanks all!

**Comment by adthrasher** [comment]
Thanks @atrull314, @drjrm3, and @drkennetz for your help on this!

**Pull request merged**
